apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deploy
  labels:
    Team: DGB-Devops
spec:
  replicas: 2
  selector:
    matchLabels:
      Team: DGB-Devops   
  template:                 
    metadata:
      labels:
        Team: DGB-Devops
    spec:  
      containers:
      - name: alpine
        image: alpine:latest
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
      nodeSelector:  
        Team: DGB-Devops
